#! /bin/bash

#define icons for workspaces 1-10
ic=(0 Browser Files Music Videos Other Steam Other Other Other Term)

#initial check for occupied workspaces
for num in $(hyprctl workspaces | rg ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export o"$num"="o_$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | rg active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export f"$num"="f_$num"
  export fnum=f"$num"
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum" # unset 'last known' focused
  num=${1:11}
  export f"$num"="f_$num"
  export fnum=f"$num"
elif [[ ${1:0:10} == "focusedmon" ]]; then # switching monitor focus
  num=${1:17}
  export f"$num"="f_$num"
elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="o_$num"
  export f"$num"="f_$num"
elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num" f"$num"
fi

#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"true\" 	\
              (button :onclick \"hyprctl dispatch workspace 1\" :onrightclick \"hyprctl dispatch workspace 1 && /home/autokludge/.config/hypr/default_app\" :class \"w $o1 $f1\" \"${ic[1]}\") \
              (button :onclick \"hyprctl dispatch workspace 2\" :onrightclick \"hyprctl dispatch workspace 2 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o2 $f2\" \"${ic[2]}\") \
              (button :onclick \"hyprctl dispatch workspace 3\" :onrightclick \"hyprctl dispatch workspace 3 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o3 $f3\" \"${ic[3]}\") \
              (button :onclick \"hyprctl dispatch workspace 4\" :onrightclick \"hyprctl dispatch workspace 4 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o4 $f4\" \"${ic[4]}\") \
              (button :onclick \"hyprctl dispatch workspace 5\" :onrightclick \"hyprctl dispatch workspace 5 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o5 $f5\" \"${ic[5]}\") \
              (button :onclick \"hyprctl dispatch movecurrentworkspacetomonitor DP-3\" :class \"move-to-left-mon\" \"⇇\") \
              (button :onclick \"hyprctl dispatch movecurrentworkspacetomonitor DP-1\" :class \"move-to-right-mon\" \"⇉\") \
              (button :onclick \"hyprctl dispatch workspace 6\" :onrightclick \"hyprctl dispatch workspace 6 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o6 $f6\" \"${ic[6]}\") \
              (button :onclick \"hyprctl dispatch workspace 7\" :onrightclick \"hyprctl dispatch workspace 7 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o7 $f7\" \"${ic[7]}\") \
              (button :onclick \"hyprctl dispatch workspace 8\" :onrightclick \"hyprctl dispatch workspace 8 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o8 $f8\" \"${ic[8]}\") \
              (button :onclick \"hyprctl dispatch workspace 9\" :onrightclick \"hyprctl dispatch workspace 9 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o9 $f9\" \"${ic[9]}\") \
              (button :onclick \"hyprctl dispatch workspace 10\" :onrightclick \"hyprctl dispatch workspace 10 && /home/autokludge/.config/hypr/default_app\"	:class \"w $o10 $f10\" \"${ic[10]}\") \
          )\
        )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
done
